import { Recipe } from "app/models/recipe";

export const SAMPLE_RECIPES: Recipe[] = [
  {
    id: "1",
    title: "Chocolate Brownie",
    score: "95",
    content: [
      "1 cup all-purpose flour",
      "2 large eggs",
      "1/2 cup granulated sugar",
      "1/2 cup unsweetened cocoa powder",
      "1 teaspoon baking powder",
      "1/4 teaspoon baking soda",
      "1 teaspoon salt",
      "1 cup milk",
      "3/4 cup vegetable oil",
      "1/2 cup unsalted butter, softened",
      "2 cups chocolate chips",
    ],
    image_url: "https://images.immediate.co.uk/production/volatile/sites/30/2020/10/Gooey-Brownies-5627e49.jpg?resize=768,574",
  },
  {
    id: "2",
    title: "Baked Almonds",
    score: "90",
    content: [
      "1 cup all-purpose flour",
      "2 large eggs",
      "1/2 cup granulated sugar",
      "1/4 cup unsweetened cocoa powder",
      "1 teaspoon baking powder",
      "1/4 teaspoon baking soda",
      "1 teaspoon salt",
      "1 cup milk",
      "1/2 cup vegetable oil",
      "1/2 cup unsalted butter, softened",
      "1 cup almonds, chopped",
    ],
    image_url: "https://www.allrecipes.com/thmb/ubezkKTj-UlQ1h_N8yIXPB6xiOI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/229881-honey-roasted-almonds-DDMFS-beauty-4x3-BG-3074-d8368f28d9694d4d9ff565b280393a36.jpg",
  },
  {
    id: "3",
    title: "Chocolate Lava Cake",
    score: "85",
    content: [
      "1 cup all-purpose flour",
      "2 large eggs",
      "1/2 cup granulated sugar",
      "1/4 cup unsweetened cocoa powder",
      "1 teaspoon baking powder",
      "1/4 teaspoon baking soda",
      "1 teaspoon salt",
      "1 cup milk",
      "1/2 cup vegetable oil",
      "1/2 cup unsalted butter, softened",
      "1 cup chocolate chips",
      "1/2 cup lava cake mix",
    ],
    image_url: "https://www.allrecipes.com/thmb/dfGgVmzpoHhrsLjxGBa_0rIWyq0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/276304lava-cakeKim-e03d3bc55516400e8d05b8d84b524b73.jpg",
  },
];
